/**
 * 生成默认表信息
 * @param tableName
 * @returns
 */
export const getNewTableInfo = (tableName: string) => {
  return {
    TabColumnStruct: [
      {
        TabName: tableName,
        FieldName: 'CreateName',
        FieldType: 11,
        IsRequire: false,
        FieldGroup: 'SystemGroup',
        EditShowWhere: '',
        FieldDesc: '创建人',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: true,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 991,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 50,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 30,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'CreateTime',
        FieldType: 41,
        IsRequire: false,
        FieldGroup: 'SystemGroup',
        EditShowWhere: '',
        FieldDesc: '创建时间',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: true,
        IsBllKey: false,
        SearchUIModel: '20',
        SortNum: 990,
        Regex: '',
        DBDefault: 20,
        DefaultValue: '',
        FieldLen: 0,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: true,
        SrchMode: 20,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'ModiName',
        FieldType: 11,
        IsRequire: false,
        FieldGroup: 'SystemGroup',
        FieldDesc: '修改人',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 998,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 50,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 10,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'ModiTime',
        FieldType: 41,
        IsRequire: false,
        FieldGroup: 'SystemGroup',
        FieldDesc: '修改时间',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 995,
        Regex: '',
        DBDefault: 20,
        DefaultValue: '',
        FieldLen: 0,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 10,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },

      {
        TabName: tableName,
        FieldName: 'ModiName',
        FieldType: 11,
        IsRequire: false,
        FieldGroup: 'SystemGroup',
        FieldDesc: '修改人',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 998,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 50,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 10,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'ModiTime',
        FieldType: 41,
        IsRequire: false,
        FieldGroup: 'SystemGroup',
        FieldDesc: '修改时间',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 995,
        Regex: '',
        DBDefault: 20,
        DefaultValue: '',
        FieldLen: 0,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 10,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
    ],
    TabPropStruct: [
      {
        TabName: tableName,
        FieldName: 'CreateName',
        FieldType: 11,
        IsRequire: false,
        FieldGroup: 'SystemGroup',
        FieldDesc: '创建人',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 991,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 50,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 10,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'CreateTime',
        FieldType: 41,
        IsRequire: false,
        FieldGroup: 'SystemGroup',
        FieldDesc: '创建时间',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '20',
        SortNum: 990,
        Regex: '',
        DBDefault: 20,
        DefaultValue: '',
        FieldLen: 0,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: true,
        SrchMode: 20,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'IsEdit',
        FieldType: 31,
        IsRequire: false,
        FieldGroup: 'Default',
        FieldDesc: '是否可编辑',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 35,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 0,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: true,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 10,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'IsLog',
        FieldType: 31,
        IsRequire: false,
        FieldGroup: 'Default',
        FieldDesc: '是否开启表日志',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 40,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 0,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: true,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 10,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'IsSys',
        FieldType: 31,
        IsRequire: false,
        FieldGroup: 'DBGroup',
        FieldDesc: '是否系统内置表',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 30,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 0,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: true,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 10,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'LogExprireDay',
        FieldType: 21,
        IsRequire: false,
        FieldGroup: 'Default',
        FieldDesc: '日志保留天数',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 50,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 0,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: true,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 10,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'LogTable',
        FieldType: 11,
        IsRequire: false,
        FieldGroup: 'Default',
        FieldDesc: '日志表名',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 45,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 50,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: true,
        IsNull: false,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 10,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'ModiName',
        FieldType: 11,
        IsRequire: false,
        FieldGroup: 'SystemGroup',
        FieldDesc: '修改人',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 998,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 50,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 10,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'ModiTime',
        FieldType: 41,
        IsRequire: false,
        FieldGroup: 'SystemGroup',
        FieldDesc: '修改时间',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 995,
        Regex: '',
        DBDefault: 20,
        DefaultValue: '',
        FieldLen: 0,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 10,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'TabCacheType',
        FieldType: 21,
        IsRequire: false,
        FieldGroup: 'Default',
        EditShowWhere: '',
        FieldDesc: '表的缓存类型',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '30',
        SortNum: 20,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 0,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: true,
        SrchMode: 30,
        IsRefTab: true,
        IsEnum: true,
        RefTab: 'Hi_DataElement',
        RefField: 'ElementValue',
        RefFields: 'ElementValue,ElementDesc',
        RefFieldDesc: '类型值,缓存描述',
        RefWhere: "Domain='TabCacheType'",
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'TabDescript',
        FieldType: 11,
        IsRequire: false,
        FieldGroup: 'Default',
        FieldDesc: '表描述',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 5,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 100,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 10,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'TabName',
        FieldType: 11,
        IsRequire: true,
        FieldGroup: 'DBGroup',
        FieldDesc: '表名',
        IsIdentity: false,
        IsPrimary: true,
        ShowDataList: true,
        IsBllKey: true,
        SearchUIModel: '',
        SortNum: 1,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 50,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: true,
        IsNull: false,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: true,
        SrchMode: 10,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'TabReName',
        FieldType: 11,
        IsRequire: false,
        FieldGroup: 'Default',
        EditShowWhere: '',
        FieldDesc: '表的别名',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: true,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 5,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 50,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 10,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'TabStatus',
        FieldType: 21,
        IsRequire: false,
        FieldGroup: 'Default',
        EditShowWhere: '',
        FieldDesc: '表状态',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '29',
        SortNum: 25,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 0,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 30,
        IsRefTab: true,
        IsEnum: true,
        RefTab: 'Hi_DataElement',
        RefField: 'ElementValue',
        RefFields: 'ElementValue,ElementDesc',
        RefFieldDesc: '状态值,状态描述',
        RefWhere: "Domain='TabStatus'",
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'TabStoreType',
        FieldType: 21,
        IsRequire: false,
        FieldGroup: 'Default',
        EditShowWhere: '',
        FieldDesc: '表存储方式',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '30',
        SortNum: 10,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 0,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: true,
        SrchMode: 30,
        IsRefTab: true,
        IsEnum: true,
        RefTab: 'Hi_DataElement',
        RefField: 'ElementValue',
        RefFields: 'ElementValue,ElementDesc',
        RefFieldDesc: '类型值,存储类型描述',
        RefWhere: "Domain='TabStoreType'",
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
      {
        TabName: tableName,
        FieldName: 'TabType',
        FieldType: 21,
        IsRequire: false,
        FieldGroup: 'Default',
        EditShowWhere: '',
        FieldDesc: '表类型',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: true,
        IsBllKey: false,
        SearchUIModel: '30',
        SortNum: 15,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 0,
        FieldDec: 0,
        SNO: '',
        SNO_NUM: '',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: true,
        SrchMode: 30,
        IsRefTab: true,
        IsEnum: true,
        RefTab: 'Hi_DataElement',
        RefField: 'ElementValue',
        RefFields: 'ElementValue,ElementDesc',
        RefFieldDesc: '类型名,描述',
        RefWhere: "Domain='TabType'",
        CreateTime: new Date(),
        CreateName: '',
        ModiTime: new Date(),
        ModiName: '',
      },
    ],
    TabProps: {
      TabName: tableName,
      TabReName: '',
      TabDescript: '',
      TabStoreType: 0,
      TabType: 0,
      TabCacheType: 0,
      TabStatus: 1,
      IsSys: true,
      IsEdit: true,
      IsLog: false,
      LogTable: '',
      LogExprireDay: 0,
      CreateTime: new Date(),
      CreateName: '',
      ModiTime: new Date(),
      ModiName: '',
    },
    TabColumns: [
      {
        TabName: 'Hi_FieldModel',
        FieldName: 'CreateName',
        FieldType: 11,
        IsRequire: false,
        FieldGroup: 'SystemGroup',
        EditShowWhere: '',
        FieldDesc: '创建人',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: true,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 991,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 50,
        FieldDec: 0,
        SNO: '          ',
        SNO_NUM: '   ',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 30,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: '2022-01-14T10:37:12.603',
        CreateName: '',
        ModiTime: '2022-02-09T11:37:21.57',
        ModiName: 'Hone',
      },
      {
        TabName: 'Hi_FieldModel',
        FieldName: 'CreateTime',
        FieldType: 41,
        IsRequire: false,
        FieldGroup: 'SystemGroup',
        EditShowWhere: '',
        FieldDesc: '创建时间',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: true,
        IsBllKey: false,
        SearchUIModel: '20',
        SortNum: 990,
        Regex: '',
        DBDefault: 20,
        DefaultValue: '',
        FieldLen: 0,
        FieldDec: 0,
        SNO: '          ',
        SNO_NUM: '   ',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: true,
        SrchMode: 20,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: '2022-01-14T10:37:12.603',
        CreateName: '',
        ModiTime: '2022-02-11T10:12:40.17',
        ModiName: 'Hone',
      },
      {
        TabName: 'Hi_FieldModel',
        FieldName: 'ModiName',
        FieldType: 11,
        IsRequire: false,
        FieldGroup: 'SystemGroup',
        FieldDesc: '修改人',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 998,
        Regex: '',
        DBDefault: 10,
        DefaultValue: '',
        FieldLen: 50,
        FieldDec: 0,
        SNO: '          ',
        SNO_NUM: '   ',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 10,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: '2022-01-14T10:37:12.603',
        CreateName: '',
        ModiTime: '2022-01-14T10:37:12.603',
        ModiName: 'Hone',
      },
      {
        TabName: 'Hi_FieldModel',
        FieldName: 'ModiTime',
        FieldType: 41,
        IsRequire: false,
        FieldGroup: 'SystemGroup',
        FieldDesc: '修改时间',
        IsIdentity: false,
        IsPrimary: false,
        ShowDataList: false,
        IsBllKey: false,
        SearchUIModel: '',
        SortNum: 995,
        Regex: '',
        DBDefault: 20,
        DefaultValue: '',
        FieldLen: 0,
        FieldDec: 0,
        SNO: '          ',
        SNO_NUM: '   ',
        IsSys: false,
        IsNull: true,
        IsIgnore: false,
        IsObsolete: false,
        IsShow: true,
        IsSearch: false,
        SrchMode: 10,
        IsRefTab: false,
        IsEnum: false,
        RefTab: '',
        RefField: '',
        RefFields: '',
        RefFieldDesc: '',
        RefWhere: '',
        CreateTime: '2022-01-14T10:37:12.603',
        CreateName: '',
        ModiTime: '2022-01-14T10:37:12.603',
        ModiName: 'Hone',
      },
    ],
  };
};
